### ISSUE TITLE
Language localization

### ISSUE THREAD

**Issue by CCCClear** [ps-dps/MobCaptains#24]
In the 1.18.2forge version I use, there are currently no lang files, which makes it impossible to localize either special items or messages.

**Comment by PuckiSilver** [comment]
That's is intended and will most likely stay like that since the whole pack is only required on the server with not even a resource pack needed.
Since I want the pack to be enjoyable without the need for anyone to install anything additionally or merge resource packs, I won’t be adding a required resource pack.
It would be possible to work with fallbacks but they were only added recently, so that would make it incompatible with older versions.
TL;DR
Yes, that's correct.
