### ISSUE TITLE
Mob Captains not working on a world made before downloading the mod. Cannot figure out how to reload

### ISSUE THREAD

**Issue by NollReed** [ps-dps/MobCaptains#40]
It works in another world, able to config all the stuff and the sorts. But cannot get it working on another world.

**Comment by PuckiSilver** [comment]
Did you ever move the world or delete anything from it?
How did you add the pack to the world?
What version of Minecraft & MobCaptains are you using?
Singleplayer or server?
Other mods or plugins?
What loader? Vanilla? Paper? Purpur? Fabric? Forge?

**Comment by NollReed** [comment]
1: Not that i know of
2: Using ATLaunchers "Add mod" button and using the Modrinth option
3: Version is 1.20.6 and the "MobCaptains-mod-v3.3.0.jar"
4: It is single player with PnP. 
5:
![image](https://github.com/user-attachments/assets/79b7573a-174c-42b2-b2f6-22eb03c3fcad)
6: Fabric

**Comment by NollReed** [comment]
![2024-08-17_22 46 32](https://github.com/user-attachments/assets/b3666509-02f4-45d2-b2c4-cdc97e36f168)
![2024-08-17_22 46 32](https://github.com/user-attachments/assets/11d89ffd-937f-417b-b4d8-e80f94ee79b3)
Working on one world but not any new world i make.

**Comment by PuckiSilver** [comment]
Weird, probably an incompatibility with one of the other mods.
You could try to run `/function ps-mob:load` to manually trigger a reload of just MobCaptains but unsure if that will help.
If that’s not it, this is most likely something I can’t fix on my end since the mod is a data pack under the hood, meaning it only relies on vanilla mechanics.

**Comment by NollReed** [comment]
Huzzah that worked fuck yea.

**Comment by NollReed** [comment]
i tried looking for a command like that but couldnt find it at all. IDK how youd do it, but something like an FAQ or "try this if its not working" could probs go miles. Or there is one and im blind

**Comment by PuckiSilver** [comment]
No, there is nothing for that specific command but the vanilla game makes sure that that command runs when joining the world/restarting the server, so it shouldn't be necessary.
Mods break a lot of things though since they can literally change everything about the game. If I revise the description or link to an faq I might include it 🤷 thanks for the suggestion.
