### ISSUE TITLE
Nerf (Raid) Farm spawns

### ISSUE THREAD

**Issue by allanonmage** [ps-dps/MobCaptains#8]
I would like to exclude mob captains from raids.  I think that is causing an issue with a raid farm.  I think Evokers are becoming captains, making them stay around a long time, and then causing Vex's to stick around and break the farm.

**Comment by allanonmage** [comment]
I found the file "captains.json" in `mob-captains-v2.1.0\data\ps-mob\tags\entity_types` but I don't really get what's going on here.  All the mobs are set to `"required": false` which seems backwards.

How can I exclude Evokers from becoming mob captains?

**Comment by PuckiSilver** [comment]
Hey,

If you only want to **disable evokers from becoming captains, you can just remove them from the `captains.json` list** you found. The `"required": false` tells the game to load the file even if that entry doesn’t exist.

the rest of the config is accessible through a chat based menu ingame because of data pack limitations.

A more permanent solution for raid mobs might follow.

**Comment by PuckiSilver** [comment]
Hey, moving forward, actually removing Mob Captains from raid farms will only be possible by removing said mobs from the list, but they should spawn less frequently in all farms in the upcoming v3.0.0 release

**Comment by allanonmage** [comment]
I had to remove evokers and pillagers, and maybe witches from being captains to get my raid farm working again.  But the config worked fine.  How do you detect if the mobs spawn in a farm or not?  We use our enderman farm to get all the goodies :D

**Comment by PuckiSilver** [comment]
The new system blocks spawns in a radius of 24 blocks around where any captain spawns for 10 minutes (the time is configurable).
That way, if a captain spawns in a farm, the whole farm won’t produce another captain for 10 minutes (or just a lot fewer if the farm is bigger).
